FROM postgres
COPY departments_schema.sql /docker-entrypoint-initdb.d/
COPY departments_data.sql /docker-entrypoint-initdb.d/
#COPY employees_data.sql /docker-entrypoint-initdb.d/
#COPY employees_schema.sql /docker-entrypoint-initdb.d/